import { IBM_Plex_Serif} from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast'

const ibmPlexSerif = IBM_Plex_Serif({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata = {
  title: "Resort Island",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ibmPlexSerif.className}>
        {children}
        <Toaster position="top-right" />
        </body>
    </html>
  );
}
